export const expertiseData = {
  '形式': [
    {image: '03-02-01.svg', title: '影片/動態', value: '0'},
    {image: '03-02-02.svg', title: '圖文/靜態', value: '1'},
  ],
	'風格': [
    {image: '03-02-03.svg', title: '幽默/強烈', value: '0'},
    {image: '03-02-04.svg', title: '知性/溫和', value: '1'},
  ],
	'合作方式': [
		{image: '03-02-05.svg', title: '專業介紹', value: '0'},
		{image: '03-02-06.svg', title: '生活美照', value: '1'},
	],
	'利潤': [
		{image: '03-02-07.svg', title: '訂單數多', value: '0'},
		{image: '03-02-08.svg', title: '單筆利潤高', value: '1'},
	],
	'實際體驗': [
		{image: '03-02-09.svg', title: '親身體驗', value: '0'},
		{image: '03-02-10.svg', title: '不需體驗', value: '1'},
	],
};
export const interestData = [
	{image: '03-03-01.svg', title: '藝術設計'},
	{image: '03-03-02.svg', title: '內容創作'},
	{image: '03-03-03.svg', title: '家電電玩'},
	{image: '03-03-04.svg', title: '3C耳機'},
	{image: '03-03-05.svg', title: '電腦週邊'},
	{image: '03-03-06.svg', title: '保健醫療'},
	{image: '03-03-07.svg', title: '美食生鮮'},
	{image: '03-03-08.svg', title: '保養彩妝'},
	{image: '03-03-09.svg', title: '服飾鞋襪'},
	{image: '03-03-10.svg', title: '精品珠寶'},
	{image: '03-03-11.svg', title: '日用餐廚'},
	{image: '03-03-12.svg', title: '寵物生活'},
	{image: '03-03-13.svg', title: '母嬰文具'},
	{image: '03-03-14.svg', title: '家具修繕'},
	{image: '03-03-15.svg', title: '戶外運動'},
	{image: '03-03-16.svg', title: '圖書影音'},
	{image: '03-03-17.svg', title: '票券服務'},
	{image: '03-03-18.svg', title: '其他商品'},
];
export const achieveData = [
	{image: '07-04-01.png', title: '認識你真好', description: '已完成所有資料設定至少一個社群連結'},
	{image: '07-04-02.png', title: '我是萬人迷', description: '社群人數達10000人'},
	{image: '07-04-03.png', title: '1星流量王', description: '代言按鈕總點擊次數累計500次'},
	{image: '07-04-04.png', title: '2星流量王', description: '代言按鈕總點擊次數累計5000次'},
	{image: '07-04-05.png', title: '3星流量王', description: '代言按鈕總點擊次數累計12000次'},
	{image: '07-04-06.png', title: '4星流量王', description: '代言按鈕總點擊次數累計_____次'},
	{image: '07-04-07.png', title: '5星流量王', description: '代言按鈕總點擊次數累計_____次'},
	{image: '07-04-08.png', title: '新手上路', description: '已完成第一次代言'},
	{image: '07-04-09.png', title: '1星小紅', description: '代言商品數累計5件'},
	{image: '07-04-10.png', title: '2星小紅', description: '代言商品數累計20件'},
	{image: '07-04-11.png', title: '3星小紅', description: '代言商品數累計50件'},
	{image: '07-04-12.png', title: '4星小紅', description: '代言商品數累計_____件'},
	{image: '07-04-13.png', title: '5星小紅', description: '代言商品數累計_____件'},
	{image: '07-04-14.png', title: '生日快樂', description: '加入小紅計畫滿1年'},
	{image: '07-04-15.png', title: '超給利', description: '已累計轉換金額達_____元'},
];
export const cityTW = [
	{ id: "台北市",	text:	"台北市" },
	{ id: "新北市",	text:	"新北市" },
	{ id: "基隆市",	text:	"基隆市" },
	{ id: "宜蘭縣",	text:	"宜蘭縣" },
	{ id: "新竹市",	text:	"新竹市" },
	{ id: "新竹縣",	text:	"新竹縣" },
	{ id: "桃園市",	text:	"桃園市" },
	{ id: "苗栗縣",	text:	"苗栗縣" },
	{ id: "台中市",	text:	"台中市" },
	{ id: "彰化縣",	text:	"彰化縣" },
	{ id: "南投縣",	text:	"南投縣" },
	{ id: "雲林縣",	text:	"雲林縣" },
	{ id: "嘉義市",	text:	"嘉義市" },
	{ id: "嘉義縣",	text:	"嘉義縣" },
	{ id: "台南市",	text:	"台南市" },
	{ id: "高雄市",	text:	"高雄市" },
	{ id: "屏東縣",	text:	"屏東縣" },
	{ id: "花蓮縣",	text:	"花蓮縣" },
	{ id: "澎湖縣",	text:	"澎湖縣" },
	{ id: "金門縣",	text:	"金門縣" },
	{ id: "連江縣",	text:	"連江縣" }
]