export const expertiseData = {
  '形式': [
    {image: '03-02-01.svg', title: '影片/動態'},
    {image: '03-02-02.svg', title: '圖文/靜態'},
  ],
	'風格': [
    {image: '03-02-03.svg', title: '幽默/強烈'},
    {image: '03-02-04.svg', title: '知性/溫和'},
  ],
	'合作方式': [
		{image: '03-02-05.svg', title: '專業介紹'},
		{image: '03-02-06.svg', title: '生活美照'},
	],
	'利潤': [
		{image: '03-02-07.svg', title: '訂單數多'},
		{image: '03-02-08.svg', title: '單筆利潤高'},
	],
	'實際體驗': [
		{image: '03-02-09.svg', title: '親身體驗'},
		{image: '03-02-10.svg', title: '不需體驗'},
	],
};
export const interestData = [
	{image: '03-03-01.svg', title: '藝術設計'},
	{image: '03-03-02.svg', title: '內容創作'},
	{image: '03-03-03.svg', title: '家電電玩'},
	{image: '03-03-04.svg', title: '3C耳機'},
	{image: '03-03-05.svg', title: '電腦週邊'},
	{image: '03-03-06.svg', title: '保健醫療'},
	{image: '03-03-07.svg', title: '美食生鮮'},
	{image: '03-03-08.svg', title: '保養彩妝'},
	{image: '03-03-09.svg', title: '服飾鞋襪'},
	{image: '03-03-10.svg', title: '精品珠寶'},
	{image: '03-03-11.svg', title: '日用餐廚'},
	{image: '03-03-12.svg', title: '寵物生活'},
	{image: '03-03-13.svg', title: '母嬰文具'},
	{image: '03-03-14.svg', title: '家具修繕'},
	{image: '03-03-15.svg', title: '戶外運動'},
	{image: '03-03-16.svg', title: '圖書影音'},
	{image: '03-03-17.svg', title: '票券服務'},
	{image: '03-03-18.svg', title: '其他商品'},
];
export const cityTW = [
	{ id: "台北市",	text:	"台北市" },
	{ id: "新北市",	text:	"新北市" },
	{ id: "基隆市",	text:	"基隆市" },
	{ id: "宜蘭縣",	text:	"宜蘭縣" },
	{ id: "新竹市",	text:	"新竹市" },
	{ id: "新竹縣",	text:	"新竹縣" },
	{ id: "桃園市",	text:	"桃園市" },
	{ id: "苗栗縣",	text:	"苗栗縣" },
	{ id: "台中市",	text:	"台中市" },
	{ id: "彰化縣",	text:	"彰化縣" },
	{ id: "南投縣",	text:	"南投縣" },
	{ id: "雲林縣",	text:	"雲林縣" },
	{ id: "嘉義市",	text:	"嘉義市" },
	{ id: "嘉義縣",	text:	"嘉義縣" },
	{ id: "台南市",	text:	"台南市" },
	{ id: "高雄市",	text:	"高雄市" },
	{ id: "屏東縣",	text:	"屏東縣" },
	{ id: "花蓮縣",	text:	"花蓮縣" },
	{ id: "澎湖縣",	text:	"澎湖縣" },
	{ id: "金門縣",	text:	"金門縣" },
	{ id: "連江縣",	text:	"連江縣" }
]